@startsalt deleteProgram-wireframe
{
    <b>DELETE ACADEMIC PROGRAM</b>
    ===
    {
        <b>Are you sure you want to delete this program?</b>
        --
        {
            <b>Code:</b> | PRG-001
            <b>Name:</b> | Industrial and Systems Engineering
            <b>Description:</b> |
            {
                Undergraduate academic program oriented
                to comprehensive training of professionals
                in industrial and systems engineering
            }}
            --
            <b>⚠️ WARNING: This action is irreversible</b>
            <i>The program and all associated information will be permanently deleted</i>
        }

        ~~

        {[Confirm deletion] | [Cancel]}
    }

    @endsalt