@startuml

left to right direction


package "Campus Management" {
actor "Schedule Administrator" as admin
    usecase createBuilding as "createBuilding()"
    usecase openBuildings as "openBuildings()"
    usecase editBuilding as "editBuilding()"
    usecase deleteBuilding as "deleteBuilding()"
    usecase createClassroom as "createClassroom()"
    usecase openClassrooms as "openClassrooms()"
    usecase editClassroom as "editClassroom()"
    usecase deleteClassroom as "deleteClassroom()"
    usecase createResource as "createResource()"
    usecase openResources as "openResources()"
    usecase editResource as "editResource()"
    usecase deleteResource as "deleteResource()"
}

admin --> (createBuilding)
admin --> (openBuildings)
admin --> (editBuilding)
admin --> (deleteBuilding)
admin --> (createClassroom)
admin --> (openClassrooms)
(editClassroom) <-- admin
(deleteClassroom) <-- admin
(createResource) <-- admin
(openResources) <-- admin
(editResource) <-- admin
(deleteResource) <-- admin

deleteBuilding .> openBuildings : <<include>>
deleteClassroom .> openClassrooms : <<include>>
deleteResource .> openResources : <<include>>

@enduml