@startuml

left to right direction

actor "Schedule Administrator" as admin

package "Program Management" {
    usecase createProgram as "createProgram()"
    usecase openPrograms as "openPrograms()"
    usecase editProgram as "editProgram()"
    usecase deleteProgram as "deleteProgram()"
}

package "Course Management" {
    usecase createCourse as "createCourse()"
    usecase openCourses as "openCourses()"
    usecase editCourse as "editCourse()"
    usecase deleteCourse as "deleteCourse()"
}

admin --> (createProgram)
admin --> (openPrograms)
admin --> (editProgram)
admin --> (deleteProgram)

(createCourse) <-- admin
(openCourses) <-- admin
(editCourse) <-- admin
(deleteCourse) <-- admin

deleteCourse .> openCourses : <<include>>
deleteProgram .> openPrograms : <<include>>

@enduml