@startuml

left to right direction

actor "Schedule Administrator" as admin
actor "Schedule Consultant" as consultant

consultant <|-up- admin 


package "Teacher Management" {
    usecase createTeacher as "createTeacher()"
    usecase openTeachers as "openTeachers()"
    usecase editTeacher as "editTeacher()"
    usecase deleteTeacher as "deleteTeacher()"
    usecase configureTeacherPreferences as "configureTeacherPreferences()"
}

package "Schedule Consultation" {
    usecase viewSchedule as "viewSchedule()"
}

package "Schedule Generation" {
    usecase generateSchedule as "generateSchedule()"
}

package "Assignments" {
    usecase assignTeacherToCourse as "assignTeacherToCourse()"
}


(createTeacher) <-- admin
(openTeachers) <-- admin
(editTeacher) <-- admin
(deleteTeacher) <-- admin
(configureTeacherPreferences) <-- admin

consultant --> (viewSchedule)

admin --> (assignTeacherToCourse)
admin --> (generateSchedule)

deleteTeacher .> openTeachers : <<include>>

@enduml