@startuml diagrama-contexto-administrador

left to right direction
skinparam linetype polyline

state "SESSION_CLOSED" as NoAuth
state "SYSTEM_AVAILABLE" as Menu

state "PROGRAMS_OPEN" as ListPrograms
state "PROGRAM_OPEN" as EditProgram
state "COURSES_OPEN" as ListCourses
state "COURSE_OPEN" as EditCourse
state "TEACHERS_OPEN" as ListTeachers
state "TEACHER_OPEN" as EditTeacher
state "TEACHER_PREFERENCES_OPEN" as EditTeacherPreferences
state "BUILDINGS_OPEN" as ListBuildings
state "BUILDING_OPEN" as EditBuilding
state "CLASSROOMS_OPEN" as ListClassrooms
state "CLASSROOM_OPEN" as EditClassroom
state "RESOURCES_OPEN" as ListResources
state "RESOURCE_OPEN" as EditResource

state "TEACHER_ASSIGNMENTS_OPEN" as Assignments
state "SCHEDULE_GENERATED" as Generation
state "SCHEDULE_OPEN" as Consultation

[*] --> NoAuth

NoAuth --> Menu : startSession()

Menu --> NoAuth : closeSession()
Menu --> ListPrograms: openPrograms()
Menu --> ListCourses: openCourses()
Menu --> ListTeachers: openTeachers()
Menu --> ListBuildings: openBuildings()
Menu --> ListClassrooms: openClassrooms()
Menu --> ListResources: openResources()
Menu --> Generation: generateSchedule()
Menu --> Consultation: viewSchedule()

EditTeacher --> Assignments: assignTeacherToCourse()

Assignments --> EditTeacher: editTeacher()


ListPrograms --> EditProgram: createProgram()
ListPrograms --> EditProgram: editProgram()
ListPrograms --> ListPrograms: deleteProgram()

EditProgram --> EditProgram: editProgram()
EditProgram --> ListPrograms: openPrograms()

ListCourses --> EditCourse: createCourse()
ListCourses --> EditCourse: editCourse()
ListCourses --> ListCourses: deleteCourse()

EditCourse --> EditCourse: editCourse()
EditCourse --> ListCourses: openCourses()

ListTeachers --> EditTeacher: createTeacher()
ListTeachers --> EditTeacher: editTeacher()
ListTeachers --> ListTeachers: deleteTeacher()

EditTeacher --> EditTeacher: editTeacher()
EditTeacher --> EditTeacherPreferences: configureTeacherPreferences()
EditTeacher --> ListTeachers: openTeachers()

EditTeacherPreferences --> EditTeacher: openTeacherEdition()


ListBuildings --> EditBuilding: createBuilding()
ListBuildings --> EditBuilding: editBuilding()
ListBuildings --> ListBuildings: deleteBuilding()
EditBuilding --> EditBuilding: editBuilding()

EditBuilding --> ListBuildings: openBuildings()

ListClassrooms --> EditClassroom: createClassroom()
ListClassrooms --> EditClassroom: editClassroom()
ListClassrooms --> ListClassrooms: deleteClassroom()

EditClassroom --> EditClassroom: editClassroom()
EditClassroom --> ListClassrooms: openClassrooms()

ListResources --> EditResource: createResource()
ListResources --> EditResource: editResource()
ListResources --> ListResources: deleteResource()

EditResource --> EditResource: editResource()
EditResource --> ListResources: openResources()

ListPrograms --> Menu: completeManagement()
ListCourses --> Menu: completeManagement()
ListTeachers --> Menu: completeManagement()
ListBuildings --> Menu: completeManagement()
ListClassrooms --> Menu: completeManagement()
ListResources --> Menu: completeManagement()
Generation --> Menu: completeProcess()
Consultation --> Menu: completeConsultation()

@enduml