@startuml createBuilding

skinparam linetype polyline

state createBuilding as "createBuilding()" {

    state " " as RequestingData
    state " " as CreandoEdificio

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests create new
    end note    
    
    RequestingData -[#green]-> CreandoEdificio
    note on link
    <b>System</b> presents solicitud de datos mínimos del edificio
    • Código del edificio (obligatorio)
    • Nombre del edificio (obligatorio)
    • Permite requestsr crear edificio
    • Permite requestsr cancelar creación
    end note
    
    CreandoEdificio -[#green]-> [*]
    note on link
    <b>Administrator</b> proporciona datos mínimos
    <b>System</b> crea edificio y transfiere a edición
    end note
}

crearEdificio -[#green]-> BUILDING_OPEN
note on link
editarEdificio(edificioNuevo)
end note

crearEdificio -[#blue]-> BUILDINGS_OPEN
note on link
cancelar creación
end note

@enduml