@startuml createBuilding

skinparam linetype polyline

state createBuilding as "createBuilding()" {

    state " " as RequestingData
    state " " as CreatingBuilding

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests create new
    end note    
    
    RequestingData -[#green]-> CreatingBuilding
    note on link
    <b>System</b> presents solicitud de datos mínimos del edificio
    • Código del edificio (obligatorio)
    • Nombre del edificio (obligatorio)
    • Permite request crear edificio
    • Permite request cancel creation
    end note
    
    CreatingBuilding -[#green]-> [*]
    note on link
    <b>Administrator</b> provides minimal data
    <b>System</b> crea edificio y transfiere a edición
    end note
}

crearEdificio -[#green]-> BUILDING_OPEN
note on link
editarEdificio(edificioNuevo)
end note

crearEdificio -[#blue]-> BUILDINGS_OPEN
note on link
cancel creation
end note

@enduml