@startuml editResource-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Recursos Abierto" as RecursosAbierto
rectangle #CDEBA5 ":Recurso Abierto" as RecursoAbierto
rectangle #CDEBA5 ":Collaboration CreateResource" as CreateResource
rectangle #CDEBA5 ":Collaboration AbrirRecursos" as AbrirRecursos

package editResource as "editResource()" {
    rectangle #629EF9 EditResourceView
    rectangle #b5bd68 RecursoController
    rectangle #F2AC4E ResourceRepository
    rectangle #F2AC4E Resource
}

RecursosAbierto --> EditResourceView: editarRecurso(recursoId)
RecursoAbierto --> EditResourceView: editarRecurso(recursoId)
CreateResource --> EditResourceView: editarRecurso(recursoNuevo)

EditResourceView -d-> RecursoController: cargarRecursoParaEdición(recursoId) : Recurso

RecursoController --> ResourceRepository: getById(recursoId) : Recurso

EditResourceView --> RecursoController: modificarCampos(recursoId, cambios) : boolean

RecursoController --> ResourceRepository: update(recurso) : boolean

ResourceRepository -- Recurso

EditResourceView ..> AbrirRecursos: <<include>> openResources()

@enduml