@startuml createTeacher-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto
rectangle #CDEBA5 ":Collaboration EditTeacher" as EditTeacher

package createTeacher as "createTeacher()" {
    rectangle #629EF9 CreateTeacherView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E Teacher
}

ProfesoresAbierto -r-> CreateTeacherView: createTeacher()

CreateTeacherView -d-> ProfesorController: validarDatosMínimos(codigo, nombres, apellidos) : boolean

ProfesorController --> TeacherRepository: verificarUnicidad(codigo) : boolean

CreateTeacherView --> ProfesorController: crearProfesor(codigo, nombres, apellidos) : Profesor

ProfesorController --> TeacherRepository: crear(codigo, nombres, apellidos) : Profesor

TeacherRepository -- Profesor

CreateTeacherView ..> EditTeacher: <<include>> editarProfesor(profesorNuevo)

@enduml