@startuml deleteCourse

skinparam linetype polyline

state deleteCourse as "deleteCourse()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoCurso

    [*] -[#green]-> ConfirmandoEliminacion 
    note on link
    <b>Administrator</b> requests delete
    end note    
    
    ConfirmandoEliminacion -[#green]-> EliminandoCurso
    note on link
    <b>System</b> presents información del curso a eliminar
    • Código, nombre, descripción del curso
    • Créditos, horas teóricas, horas prácticas
    • Programa académico asociado
    • Presenta advertencia de eliminación
    • Permite request confirmar eliminación
    • Permite request cancelar eliminación
    end note
    
    EliminandoCurso -[#green]-> [*]
    note on link
    <b>Administrator</b> requests confirmación de eliminación
    <b>System</b> permite request confirmar eliminación
    <b>Administrator</b> requests confirmar eliminación
    end note
}

eliminarCurso -[#green]-> COURSES_OPEN
note on link
<<include>> openCourses() - lista actualizada
end note

eliminarCurso -[#blue]-> COURSES_OPEN
note on link
<<include>> openCourses() - cancelar eliminación
end note

@enduml