@startuml deleteResource-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Recursos Abierto" as RecursosAbierto
rectangle #CDEBA5 ":Recurso Abierto" as RecursoAbierto
rectangle #CDEBA5 ":Collaboration AbrirRecursos" as AbrirRecursos

package deleteResource as "deleteResource()" {
    rectangle #629EF9 DeleteResourceView
    rectangle #b5bd68 RecursoController
    rectangle #F2AC4E ResourceRepository
    rectangle #F2AC4E Resource
}

RecursosAbierto --> DeleteResourceView: eliminarRecurso(recursoId)
RecursoAbierto --> DeleteResourceView: eliminarRecurso(recursoId)

DeleteResourceView -d-> RecursoController: cargarRecursoParaEliminación(recursoId) : Recurso

RecursoController --> ResourceRepository: getById(recursoId) : Recurso

ResourceRepository -- Recurso

DeleteResourceView --> RecursoController: eliminarRecurso(recursoId) : void

RecursoController --> ResourceRepository: delete(recursoId) : void

DeleteResourceView ..> AbrirRecursos: <<include>> openResources()

@enduml