@startuml generateSchedule

skinparam linetype polyline

state generateSchedule as "generateSchedule()" {

    state " " as RequiringGeneration
    state " " as ProvidingConfirmation
    state c <<choice>>

    [*] -[#green]-> RequiringGeneration 
    note on link
    <b>Administrator</b> requests generar horario
    end note    
    
    RequiringGeneration -[#green]-> ProvidingConfirmation
    note on link
    <b>System</b> presents
    • datos disponibles para generación
    • advertencia si horario existe
    end note
    
    ProvidingConfirmation -[#green]-> c
    note on link
    <b>Administrator</b> requests
    • confirmar generación
    • cancelar generación
    end note
    
    c -[#red]-> [*]
    note on link
    Administrador cancela
    end note

    c -[#green]-> [*]
    note on link
    datos insuficientes
    end note

    c -[#green]-> [*]
    note on link
    generación exitosa
    end note
}

generarHorario -[#green]-> SCHEDULE_OPEN
note on link
viewSchedule()
end note

@enduml