@startuml createCourse-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Cursos Abierto" as CursosAbierto
rectangle #CDEBA5 ":Collaboration EditCourse" as EditCourse

package createCourse as "createCourse()" {
    rectangle #629EF9 CreateCourseView
    rectangle #b5bd68 CursoController
    rectangle #F2AC4E CourseRepository
    rectangle #F2AC4E Course
}

CursosAbierto --> CreateCourseView: createCourse()

CreateCourseView -d-> CursoController: validarDatosMínimos(nombre) : boolean

CursoController --> CourseRepository: verificarUnicidad(nombre) : boolean

CreateCourseView --> CursoController: crearCurso(nombre) : Curso

CursoController --> CourseRepository: crear(nombre) : Curso

CourseRepository -- Curso

CreateCourseView ..> EditCourse: <<include>> editarCurso(cursoNuevo)

@enduml