@startuml createCourse-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Courses Open" as CoursesOpen
rectangle #CDEBA5 ":Collaboration EditCourse" as EditCourse

package createCourse as "createCourse()" {
    rectangle #629EF9 CreateCourseView
    rectangle #b5bd68 CoursesController
    rectangle #F2AC4E CourseRepository
    rectangle #F2AC4E Course
}

CoursesOpen --> CreateCourseView: createCourse()

CreateCourseView -d-> CoursesController: validateMinimalData(name) : boolean

CoursesController --> CourseRepository: checkUniqueness(name) : boolean

CreateCourseView --> CoursesController: createCourse(name) : Course

CoursesController --> CourseRepository: create(name) : Course

CourseRepository -- Course

CreateCourseView ..> EditCourse: <<include>> editCourse(newCourse)

@enduml