@startuml editBuilding-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Edificios Abierto" as EdificiosAbierto
rectangle #CDEBA5 ":Edificio Abierto" as EdificioAbierto
rectangle #CDEBA5 ":Collaboration CreateBuilding" as CreateBuilding
rectangle #CDEBA5 ":Collaboration AbrirEdificios" as AbrirEdificios

package editBuilding as "editBuilding()" {
    rectangle #629EF9 EditBuildingView
    rectangle #b5bd68 EdificioController
    rectangle #F2AC4E BuildingRepository
    rectangle #F2AC4E Building
}

EdificiosAbierto --> EditBuildingView: editarEdificio(edificioId)
EdificioAbierto --> EditBuildingView: editarEdificio(edificioId)
CreateBuilding --> EditBuildingView: editarEdificio(edificioNuevo)

EditBuildingView -d-> EdificioController: cargarEdificioParaEdición(edificioId) : Edificio

EdificioController --> BuildingRepository: getById(edificioId) : Edificio

EditBuildingView --> EdificioController: modificarCampos(edificioId, cambios) : boolean

EdificioController --> BuildingRepository: update(edificio) : boolean

BuildingRepository -- Edificio

EditBuildingView ..> AbrirEdificios: <<include>> openBuildings()

@enduml