@startsalt editProgram-wireframe
{
    <b>ACADEMIC PROGRAM EDITING</b>
    ===
    {
        <b>Program code:</b> | [      PRG-001      ]
        <b>Program name:</b> | [                                              ]
        <b>Description:</b> | 
        {
            [                                                                    ]
            [                                                                    ]
            [                                                                    ]
        }
    }
    
    ~~
    
    {[Save] | [Save and exit] | [Cancel editing]}
}

@endsalt