@startsalt deleteClassroom-wireframe
{
    <b>DELETE CLASSROOM</b>
    ===
    {
        <b>Are you sure you want to delete this classroom?</b>
        --
        {
            {<b>Code:</b> | AULA-001
            <b>Name:</b> | Main Auditorium}
            {<b>Building:</b> | Central Building
            <b>Capacity:</b> | 120 students}
            {<b>Type:</b> | Lecture hall
            <b>Resources:</b> | Projector, Audio, AC}
            {<b>Observations:</b> |
            {
                Large capacity classroom for special
                events and lectures. Complete
                audiovisual equipment available.
            }}
            --
            <b>⚠️ WARNING: This action is irreversible</b>
            <i>The classroom and all associated information will be permanently deleted</i>
        }

        ~~

        {[Confirm deletion] | [Cancel]}
    }
}
@endsalt