@startuml logout-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":System Available" as SystemAvailable
package logout as "logout()" {
    rectangle #629EF9 LogoutView
    rectangle #b5bd68 CerrarSessionController
    rectangle #F2AC4E SesionRepository
    rectangle #F2AC4E Sesion
    rectangle #F2AC4E Usuario
}

rectangle #CDEBA5 ":Collaboration SESION_CERRADA" as SESION_CERRADA

SystemAvailable -r-> LogoutView : cerrarSesion(Usuario)

LogoutView -d-> CerrarSessionController: solicitarCierre(Usuario)

'CerrarSessionController --> Sesion: getUsuario() : Usuario
'CerrarSessionController --> LogoutView: mostrarConfirmacion()
CerrarSessionController --> SesionRepository: terminarSesion(Usuario)
SesionRepository --> Sesion: destruirSesion(Usuario)

Sesion -d- Usuario

LogoutView ..r.> SESION_CERRADA: logout()

@enduml