@startsalt assignTeacherToCourse-wireframe
{
    <b>ASSIGN COURSES TO TEACHER</b>
    ===
    {
        {
        {
            {
            <b>Available courses:</b>|<b>Assigned courses:</b>
            "Mathematics I             "|"Mathematics II            " 
            "Physics I                 "|"Physics II                "
            "General Chemistry         "|"Algorithms and Structures "
            "Differential Calculus     "|"Database I                "
            "Basic Statistics          "|"                          "
            "World History             "|"                          "
        }
        
        ~~
        
        {[Assign >>] | [<< Unassign]}
        
        ~~
        
        <b>Assignment summary:</b>
        {
            "Total available courses: 10   "
            "Total assigned courses: 4    "
            "Teacher: Dr. Manuel Masías   "
        }
        }
        }

        ~~

        {[Save assignments] | [Continue managing] | [Cancel]}
    }
}
@endsalt