@startsalt asignarProfesorACurso-wireframe
{
    <b>ASIGNAR CURSOS AL PROFESOR</b>
    ===
    {
        {
        {
            {
            <b>Cursos disponibles:</b>|<b>Cursos asignados:</b>
            "Matemática I              "|"Matemática II             " 
            "Física I                  "|"Física II                 "
            "Química General           "|"Algoritmos y Estructuras  "
            "Cálculo Diferencial       "|"Base de Datos I           "
            "Estadística Básica        "|"                          "
            "Historia Universal        "|"                          "
        }
        
        ~~
        
        {[Asignar >>] | [<< Desasignar]}
        
        ~~
        
        <b>Resumen de asignaciones:</b>
        {
            "Total cursos disponibles: 10 "
            "Total cursos asignados: 4    "
            "Profesor: Dr. Manuel Masías  "
        }
        }
        }

        ~~

        {[Guardar asignaciones] | [Continuar gestionando] | [Cancelar]}
    }
}
@endsalt