@startuml createProgram

skinparam linetype polyline

state createProgram as "createProgram()" {

    state " " as RequestingData
    state " " as CreandoPrograma

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests create new
    end note    
    
    RequestingData -[#green]-> CreandoPrograma
    note on link
    <b>System</b> requests datos mínimos del programa
    • Nombre del programa (obligatorio)
    • Permite requestsr crear programa
    • Permite requestsr cancelar creación
    end note
    
    CreandoPrograma -[#green]-> [*]
    note on link
    <b>Administrator</b> proporciona datos mínimos
    <b>System</b> crea programa y transfiere a edición
    end note
}

crearPrograma -[#green]-> PROGRAM_OPEN
note on link
editarPrograma(programaNuevo)
end note

crearPrograma -[#blue]-> PROGRAMS_OPEN
note on link
cancelar creación
end note

@enduml