@startuml openPrograms

skinparam linetype polyline

state openPrograms as "openPrograms()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests abrir programas
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents program list
    • Código, nombre, descripción de cada programa
    • Permite requestsr filter list
    • Permite requestsr create new
    • Permite requestsr delete
    • Permite requestsr edit
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

abrirProgramas -[#green]-> PROGRAM_OPEN
note on link
editProgram()
end note

abrirProgramas -[#green]-> PROGRAM_OPEN
note on link
createProgram()
end note

abrirProgramas -[#green]-> PROGRAMS_OPEN
note on link
deleteProgram()
end note

abrirProgramas -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml