@startuml completeManagement

skinparam linetype polyline

state completeManagement as "completeManagement()" {

    state " " as PresentandoMenu
    state " " as EsperandoSeleccion

    [*] -[#green]-> PresentandoMenu 
    note on link
    <b>Administrator</b> requests disponibilizar sistema
    end note    
    
    PresentandoMenu -[#green]-> EsperandoSeleccion
    note on link
    <b>System</b> permite requestsr:
    • openPrograms()
    • openCourses()
    • openTeachers()
    • openBuildings()
    • openClassrooms()
    • openResources()
    • assignTeacherToCourse()
    • generateSchedule()
    • viewSchedule()
    • logout()
    end note
    
    EsperandoSeleccion -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

completarGestion -[#green]-> PROGRAMS_OPEN
note on link
openPrograms()
end note

completarGestion -[#green]-> COURSES_OPEN
note on link
openCourses()
end note

completarGestion -[#green]-> TEACHERS_OPEN
note on link
openTeachers()
end note

completarGestion -[#green]-> BUILDINGS_OPEN
note on link
openBuildings()
end note

completarGestion -[#green]-> CLASSROOMS_OPEN
note on link
openClassrooms()
end note

completarGestion -[#green]-> RECOURSES_OPEN
note on link
openResources()
end note

completarGestion -[#green]-> TEACHER_ASSIGNMENTS_OPEN
note on link
assignTeacherToCourse()
end note

completarGestion -[#green]-> SCHEDULE_GENERATED
note on link
generateSchedule()
end note

completarGestion -[#green]-> SCHEDULE_OPEN
note on link
viewSchedule()
end note

completarGestion -[#green]-> SESSION_CLOSED
note on link
logout()
end note

@enduml