@startsalt configureTeacherPreferences-wireframe
{
    <b>CONFIGURE TEACHER PREFERENCES</b>
    ===
    {
        <b>Resource priority order:</b>
        --
        {
            {
            {<b>Priority 1:</b> | "Digital Projector            "
            <b>Priority 2:</b> | "Computer                      "}
            {<b>Priority 3:</b> | "Smart Board                   "
            <b>Priority 4:</b> | "Audio Equipment               "}
            {<b>Priority 5:</b> | "Internet Access               "
            <b>Priority 6:</b> | "Air Conditioning              "}
            {<b>Priority 7:</b> | "Specialized Laboratory        "
            <b>Observations:</b> |
                {"Preference configuration for
                schedule generation algorithm optimization
                according to teacher resources           "}}
            }
        }

        ~~

        {[Save configuration] | [Continue configuring] | [Cancel]}
    }
}
@endsalt