@startuml deleteBuilding

skinparam linetype polyline

state deleteBuilding as "deleteBuilding()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoEdificio

    [*] -[#green]-> ConfirmandoEliminacion 
    note on link
    <b>Administrator</b> requests delete
    end note    
    
    ConfirmandoEliminacion -[#green]-> EliminandoEdificio
    note on link
    <b>System</b> presents información del edificio a eliminar
    • Código, nombre del edificio
    • Ubicación, descripción
    • Observaciones, aulas asociadas
    • Presenta advertencia de eliminación
    • Permite request confirmar eliminación
    • Permite request cancelar eliminación
    end note
    
    EliminandoEdificio -[#green]-> [*]
    note on link
    <b>Administrator</b> requests confirmación de eliminación
    <b>System</b> permite request confirmar eliminación
    <b>Administrator</b> requests confirmar eliminación
    end note
}

deleteBuilding -[#green]-> BUILDINGS_OPEN
note on link
<<include>> openBuildings() - lista actualizada
end note

deleteBuilding -[#blue]-> BUILDINGS_OPEN
note on link
<<include>> openBuildings() - cancelar eliminación
end note

@enduml