@startuml createBuilding-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Edificios Abierto" as EdificiosAbierto
rectangle #CDEBA5 ":Collaboration EditBuilding" as EditBuilding

package createBuilding as "createBuilding()" {
    rectangle #629EF9 CreateBuildingView
    rectangle #b5bd68 EdificioController
    rectangle #F2AC4E BuildingRepository
    rectangle #F2AC4E Building
}

EdificiosAbierto -r-> CreateBuildingView: createBuilding()

CreateBuildingView -d-> EdificioController: validarDatosMínimos(codigo, nombre) : boolean

EdificioController --> BuildingRepository: verificarUnicidad(codigo) : boolean

CreateBuildingView --> EdificioController: crearEdificio(codigo, nombre) : Edificio

EdificioController --> BuildingRepository: crear(codigo, nombre) : Edificio

BuildingRepository -- Edificio

CreateBuildingView ..> EditBuilding: <<include>> editarEdificio(edificioNuevo)

@enduml