@startsalt openBuildings-wireframe
{ 
<b>BUILDINGS MANAGEMENT</b>  
===
{+  ID | NAME | ACTION
  --|--|--
  001 | Main Building | [Edit]
  002 | Classrooms Building | [Edit]
  003 | Laboratories Building | [Edit]
  004 | Administration Building | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt