@startuml deleteBuilding-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Edificios Abierto" as EdificiosAbierto
rectangle #CDEBA5 ":Edificio Abierto" as EdificioAbierto
rectangle #CDEBA5 ":Collaboration AbrirEdificios" as AbrirEdificios

package deleteBuilding as "deleteBuilding()" {
    rectangle #629EF9 DeleteBuildingView
    rectangle #b5bd68 EdificioController
    rectangle #F2AC4E BuildingRepository
    rectangle #F2AC4E Building
}

EdificiosAbierto --> DeleteBuildingView: eliminarEdificio(edificioId)
EdificioAbierto --> DeleteBuildingView: eliminarEdificio(edificioId)

DeleteBuildingView -d-> EdificioController: cargarEdificioParaEliminacion(edificioId) : Edificio

EdificioController --> BuildingRepository: getById(edificioId) : Edificio

BuildingRepository -- Edificio

DeleteBuildingView --> EdificioController: eliminarEdificio(edificioId) : void

EdificioController --> BuildingRepository: delete(edificioId) : void

DeleteBuildingView ..> AbrirEdificios: <<include>> openBuildings()

@enduml