@startsalt openTeachers-wireframe
{ 
<b>TEACHERS MANAGEMENT</b>  
===
{+  CODE | FIRST NAME | LAST NAME | ACTION
  --|--|--|--
  RC001 | Roberto | Castro Chirinos | [Editar]
  JM002 | José María | González López | [Editar]  
  PXYZ | Teacher first name | Teacher last name | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt