@startuml editCourse-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Cursos Abierto" as CursosAbierto
rectangle #CDEBA5 ":Curso Abierto" as CursoAbierto
rectangle #CDEBA5 ":Collaboration CreateCourse" as CreateCourse
rectangle #CDEBA5 ":Collaboration AbrirCursos" as AbrirCursos

package editCourse as "editCourse()" {
    rectangle #629EF9 EditCourseView
    rectangle #b5bd68 CursoController
    rectangle #F2AC4E CourseRepository
    rectangle #F2AC4E Course
}

CursosAbierto --> EditCourseView: editarCurso(cursoId)
CursoAbierto --> EditCourseView: editarCurso(cursoId)
CreateCourse --> EditCourseView: editarCurso(cursoNuevo)

EditCourseView -d-> CursoController: cargarCursoParaEdición(cursoId) : Curso

CursoController --> CourseRepository: getById(cursoId) : Curso

EditCourseView --> CursoController: modificarCampos(cursoId, cambios) : boolean

CursoController --> CourseRepository: update(curso) : boolean

CourseRepository -- Curso

EditCourseView ..> AbrirCursos: <<include>> openCourses()

@enduml