@startuml openClassrooms

skinparam linetype polyline

state openClassrooms as "openClassrooms()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests abrir aulas
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents classroom list
    • ID, nombre, capacidad, edificio de cada aula
    • Permite requestsr filter list
    • Permite requestsr crear aula nueva
    • Permite requestsr delete
    • Permite requestsr edit
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

abrirAulas -[#green]-> AULA_ABIERTO
note on link
editClassroom()
end note

abrirAulas -[#green]-> AULA_ABIERTO
note on link
createClassroom()
end note

abrirAulas -[#green]-> CLASSROOMS_OPEN
note on link
deleteClassroom()
end note

abrirAulas -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml