@startuml openClassrooms

skinparam linetype polyline

state openClassrooms as "openClassrooms()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests open classrooms
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents classroom list
    • ID, nombre, capacidad, edificio de cada aula
    • Permite request filter list
    • Permite request crear aula nueva
    • Permite request delete
    • Permite request edit
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

openClassrooms -[#green]-> CLASSROOM_OPEN
note on link
editClassroom()
end note

openClassrooms -[#green]-> CLASSROOM_OPEN
note on link
createClassroom()
end note

openClassrooms -[#green]-> CLASSROOMS_OPEN
note on link
deleteClassroom()
end note

openClassrooms -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml