@startuml openResources

skinparam linetype polyline

state openResources as "openResources()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests abrir recursos
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents resource list
    • ID, nombre, descripción de cada recurso
    • Permite request filter list
    • Permite request create new
    • Permite request delete
    • Permite request edit
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

abrirRecursos -[#green]-> RECOURSE_OPEN
note on link
editResource()
end note

abrirRecursos -[#green]-> RECOURSE_OPEN
note on link
createResource()
end note

abrirRecursos -[#green]-> RECOURSES_OPEN
note on link
deleteResource()
end note

abrirRecursos -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml