@startuml createProgram-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Programas Abierto" as ProgramasAbierto
rectangle #CDEBA5 ":Collaboration EditProgram" as EditProgram

package createProgram as "createProgram()" {
    rectangle #629EF9 CreateProgramView
    rectangle #b5bd68 ProgramaController
    rectangle #F2AC4E ProgramRepository
    rectangle #F2AC4E Program
}

ProgramasAbierto --> CreateProgramView: createProgram()

CreateProgramView -d-> ProgramaController: crearProgramaMinimo(nombre) : Programa

ProgramaController --> ProgramRepository: crear(nombre) : Programa

ProgramRepository -- Programa

CreateProgramView ..> EditProgram: editarPrograma(programaNuevo)

@enduml