@startuml editClassroom

skinparam linetype polyline

state editClassroom as "editClassroom()" {

    state " " as EditingData
    state " " as SavingData 

    [*] -[#green]-> EditingData 
    note on link
    <b>Administrator</b> requests edit
    end note    
    
    EditingData -[#green]-> SavingData
    note on link
    <b>System</b> presents editing data
    • Code, name of classroom
    • Associated building, capacity
    • Classroom type, resources
    • Classroom observations
    
    <b>System</b> allows request:
    • modify fields
    • save classroom
    • cancel editing
    end note
    
    SavingData -[#green]-> EditingData
    note on link
    <b>Administrator</b> requests modify fields
    end note
    
    SavingData -[#green]-> [*]
    note on link
    <b>Administrator</b> requests save and exit
    end note

    SavingData -[#red]-> [*]
    note on link
    <b>Administrator</b> requests cancel editing
    end note

}

editClassroom -[#green]-> CLASSROOMS_OPEN
note on link
openClassrooms()
end note

editClassroom -[#red]-> CLASSROOMS_OPEN
note on link
cancel editing
end note

@enduml