@startsalt editClassroom-wireframe
{
    <b>EDIT CLASSROOM</b>
    ===
    {
        <b>Classroom data:</b>
        --
        {
            {
            {<b>Code:</b> | "AULA-001                    "
            <b>Name:</b> | "Main Auditorium              "}
            {<b>Building:</b> | ^"Central Building"^
            <b>Capacity:</b> | "120                          "}
            {<b>Type:</b> | ^"Lecture hall"^
            <b>Resources:</b> | "Projector, Audio, AC         "}
            {<b>Observations:</b> |
                {"Large capacity classroom for special
                events and lectures. Complete audiovisual
                equipment available                   "}}
            }
        }

        ~~

        {[Save changes] | [Continue editing] | [Cancel]}
    }
}
@endsalt