@startuml login

skinparam linetype polyline

state login as "login()" {

    state " " as SolicitandoAcceso
    state " " as ProporcionandoCredenciales  
    state c <<choice>>

    [*] -[#green]-> SolicitandoAcceso 
    note on link
    <b>UsuarioNoRegistrado</b> requests acceder al sistema
    end note    
    
    SolicitandoAcceso -[#green]-> ProporcionandoCredenciales
    note on link
    <b>System</b> permite introducir
    • usuario
    • contraseña
    end note
    
    ProporcionandoCredenciales -[#green]-> c
    note on link
    <b>UsuarioNoRegistrado</b> introduce
    • usuario
    • contraseña
    end note
    
    c -[#red]-> SolicitandoAcceso
    note on link
    usuario:contraseña no válida
    end note

    c -[#green]-> [*]
    note on link
    usuario:contraseña válida
    end note
}

iniciarSesion -[#green]-> SYSTEM_AVAILABLE
note on link
UsuarioNoRegistrado → Administrador
completeManagement()
end note

@enduml