@startuml deleteClassroom-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Aulas Abierto" as AulasAbierto
rectangle #CDEBA5 ":Aula Abierta" as AulaAbierta
rectangle #CDEBA5 ":Collaboration AbrirAulas" as AbrirAulas

package deleteClassroom as "deleteClassroom()" {
    rectangle #629EF9 DeleteClassroomView
    rectangle #b5bd68 AulaController
    rectangle #F2AC4E ClassroomRepository
    rectangle #F2AC4E Classroom
}

AulasAbierto --> DeleteClassroomView: eliminarAula(aulaId)
AulaAbierta --> DeleteClassroomView: eliminarAula(aulaId)

DeleteClassroomView -d-> AulaController: cargarAulaParaEliminacion(aulaId) : Aula

AulaController --> ClassroomRepository: getById(aulaId) : Aula

ClassroomRepository -- Aula

DeleteClassroomView --> AulaController: eliminarAula(aulaId) : void

AulaController --> ClassroomRepository: delete(aulaId) : void

DeleteClassroomView ..> AbrirAulas: <<include>> openClassrooms()

@enduml