@startuml configureTeacherPreferences

skinparam linetype polyline

state configureTeacherPreferences as "configureTeacherPreferences()" {

    state " " as ConfiguringPreferences
    state " " as GuardandoConfiguracion 

    [*] -[#green]-> ConfiguringPreferences 
    note on link
    <b>Administrator</b> requests configurar preferencias del profesor
    end note    
    
    ConfiguringPreferences -[#green]-> GuardandoConfiguracion
    note on link
    <b>System</b> presents datos de configuración
    • Lista de recursos disponibles
    • Orden de prioridad actual del profesor
    
    <b>System</b> permite request:
    • modificar orden
    • guardar configuración
    • cancelar configuración
    end note
    
    GuardandoConfiguracion -[#green]-> ConfiguringPreferences
    note on link
    <b>Administrator</b> requests modificar orden
    end note
    
    GuardandoConfiguracion -[#green]-> [*]
    note on link
    <b>Administrator</b> requests guardar y salir
    end note

    GuardandoConfiguracion -[#red]-> [*]
    note on link
    <b>Administrator</b> requests cancelar configuración
    end note

}

configurarPreferenciasProfesor -[#green]-> TEACHER_OPEN
note on link
editTeacher()
end note

configurarPreferenciasProfesor -[#red]-> TEACHER_OPEN
note on link
cancelar configuración
end note

@enduml