@startuml openCourses-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":System Available" as SystemAvailable
package openCourses as "openCourses()" {
    rectangle #629EF9 OpenCoursesView
    rectangle #b5bd68 CoursesController
    rectangle #F2AC4E CourseRepository
    rectangle #F2AC4E Course
}

rectangle #CDEBA5 ":System Available" as SystemAvailableOutput
rectangle #CDEBA5 ":Collaboration CreateCourse" as CreateCourse
rectangle #CDEBA5 ":Collaboration EditCourse" as EditCourse
rectangle #CDEBA5 ":Collaboration DeleteCourse" as DeleteCourse

SystemAvailable -r-> OpenCoursesView: openCourses()

OpenCoursesView -d-> CoursesController: listCourses() : List<Course>

CoursesController --> CourseRepository: getAll() : List<Course>

CourseRepository -- Course

OpenCoursesView --> CoursesController: filterCourses(criteria) : List<Course>

CoursesController --> CourseRepository: findByCriteria(criteria) : List<Course>

OpenCoursesView ..> SystemAvailableOutput: completeManagement()
OpenCoursesView ..> CreateCourse: createCourse()
OpenCoursesView ..> EditCourse: editCourse()
OpenCoursesView ..> DeleteCourse: deleteCourse()

@enduml