@startsalt createBuilding-wireframe
{
    <b>CREATE BUILDING</b>
    ===
    {
        <b>Building minimum data:</b>
        --
        {
            <b>Building code (*):</b>
            "                                        "
            <b>Building name (*):</b>
            "                                        "
            --
            <i>(*) Required fields</i>
            <i>Other data will be completed during editing</i>
        }

        ~~

        {[Create building] | [Cancel]}
    }
}
@endsalt