@startsalt completeManagement-wireframe
{
    ====
    SigHor - Sistema Generador de Horarios
    ====
    {^" Main Menu "
        .
        **Master Data Management**
        [Manage Programs]
        [Manage Courses]
        [Manage Teachers]
        [Manage Buildings]
        [Manage Classrooms]
        [Manage Resources]
        .
        **Special Features**
        [Assign Teachers]
        [Generate Schedule]
        [View Schedule]
        .
        **System**
        [Close Session]
    }
    ====
    User: Administrator
    ====
}
@endsalt