@startuml diagrama-contexto-administrador

left to right direction
skinparam linetype polyline

<style>
legend {
  BackGroundColor #f0f0f0;
  'Margin 30
  Padding 10
}
footer {
  HorizontalAlignment left
}

</style>

legend top
    **DASHBOARD DE CONTEXTO** - <i>Casos de uso</i>
    '====
    |<#gray>     | Identificado |<#red>     | Requisitado |<#darkgoldenrod>     | Analizado |<#green>     | Diseñado |<#lightblue>     |Desarrollado|<#blue>     | Probado |<#black>     | Completado |
    '====
    '[**nombreCasoUso()**] -> Especificación detallada / [**A**] -> Análisis MVC
    '====
end legend

footer
**<i>[[https://github.com/mmasias/pySigHor << Volver al repo]]</i>** 
end footer

state "SESSION_CLOSED" as NoAuth
state "SYSTEM_AVAILABLE" as Menu

state "PROGRAMS_OPEN" as ListProgramas
state "PROGRAM_OPEN" as EditPrograma
state "COURSES_OPEN" as ListCursos
state "COURSE_OPEN" as EditCurso
state "TEACHERS_OPEN" as ListProfesores
state "TEACHER_OPEN" as EditProfesor
state "TEACHER_PREFERENCES_OPEN" as EditProfesorPreferencias
state "BUILDINGS_OPEN" as ListEdificios
state "BUILDING_OPEN" as EditEdificio
state "CLASSROOMS_OPEN" as ListAulas
state "CLASSROOM_OPEN" as EditAula
state "RECOURSES_OPEN" as ListRecursos
state "RECOURSE_OPEN" as EditRecurso

state "TEACHER_ASSIGNMENTS_OPEN" as Asignaciones
state "SCHEDULE_GENERATED" as Generacion
state "SCHEDULE_OPEN" as Consulta

NoAuth -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/login/README.md login()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/login/README.md A]]

Menu -[#darkgoldenrod,thickness=2]-> NoAuth: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/logout/README.md logout()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/logout/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openPrograms/README.md openPrograms()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openPrograms/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openCourses/README.md openCourses()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openCourses/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openTeachers/README.md openTeachers()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openTeachers/README.md A]]
Menu -[#darkgoldenrod]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openBuildings/README.md openBuildings()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openBuildings/README.md A]]
Menu -[#darkgoldenrod]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openClassrooms/README.md openClassrooms()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openClassrooms/README.md A]]
Menu -[#darkgoldenrod]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openResources/README.md openResources()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openResources/README.md A]]
Menu -[#darkgoldenrod,bold]-> Generacion: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/generateSchedule/README.md generateSchedule()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/generateSchedule/README.md A]]
Menu -[#darkgoldenrod,bold]-> Consulta: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/viewSchedule/README.md viewSchedule()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/viewSchedule/README.md A]]

EditProfesor -[#darkgoldenrod,thickness=2]-> Asignaciones: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/assignTeacherToCourse/README.md assignTeacherToCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/assignTeacherToCourse/README.md A]]

Asignaciones -[#darkgoldenrod,thickness=2]-> Asignaciones: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/assignTeacherToCourse/README.md assignTeacherToCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/assignTeacherToCourse/README.md A]]
Asignaciones -[#darkgoldenrod,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editTeacher/README.md editTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editTeacher/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createProgram/README.md createProgram()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createProgram/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editProgram/README.md editProgram()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editProgram/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteProgram/README.md deleteProgram()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteProgram/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editProgram/README.md editProgram()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editProgram/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteProgram/README.md deleteProgram()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteProgram/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openPrograms/README.md openPrograms()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openPrograms/README.md A]]
ListCursos -[#darkgoldenrod,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createCourse/README.md createCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createCourse/README.md A]]
ListCursos -[#darkgoldenrod,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editCourse/README.md editCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editCourse/README.md A]]
ListCursos -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteCourse/README.md deleteCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteCourse/README.md A]]
EditCurso -[#darkgoldenrod,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editCourse/README.md editCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editCourse/README.md A]]
EditCurso -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteCourse/README.md deleteCourse()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteCourse/README.md A]]
EditCurso -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openCourses/README.md openCourses()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openCourses/README.md A]]
ListProfesores -[#darkgoldenrod,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createTeacher/README.md createTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createTeacher/README.md A]]
ListProfesores -[#darkgoldenrod,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editTeacher/README.md editTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editTeacher/README.md A]]
ListProfesores -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteTeacher/README.md deleteTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteTeacher/README.md A]]
EditProfesor -[#darkgoldenrod,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editTeacher/README.md editTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editTeacher/README.md A]]
EditProfesor -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteTeacher/README.md deleteTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteTeacher/README.md A]]
EditProfesor -[#darkgoldenrod,thickness=2]-> EditProfesorPreferencias: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/configureTeacherPreferences/README.md configureTeacherPreferences()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/configureTeacherPreferences/README.md A]]
EditProfesor -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openTeachers/README.md openTeachers()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openTeachers/README.md A]]
EditProfesorPreferencias -[#darkgoldenrod,thickness=2]-> EditProfesorPreferencias: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/configureTeacherPreferences/README.md configureTeacherPreferences()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/configureTeacherPreferences/README.md A]]
EditProfesorPreferencias -[#darkgoldenrod,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editTeacher/README.md editTeacher()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editTeacher/README.md A]]
ListEdificios -[#darkgoldenrod,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createBuilding/README.md createBuilding()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createBuilding/README.md A]]
ListEdificios -[#darkgoldenrod,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editBuilding/README.md editBuilding()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editBuilding/README.md A]]
ListEdificios -[#darkgoldenrod,bold]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteBuilding/README.md deleteBuilding()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteBuilding/README.md A]]
EditEdificio -[#darkgoldenrod,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editBuilding/README.md editBuilding()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editBuilding/README.md A]]
EditEdificio -[#darkgoldenrod,bold]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteBuilding/README.md deleteBuilding()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteBuilding/README.md A]]
EditEdificio -[#darkgoldenrod]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openBuildings/README.md openBuildings()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openBuildings/README.md A]]
ListAulas -[#darkgoldenrod,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createClassroom/README.md createClassroom()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createClassroom/README.md A]]
ListAulas -[#darkgoldenrod,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editClassroom/README.md editClassroom()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editClassroom/README.md A]]
ListAulas -[#darkgoldenrod,bold]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteClassroom/README.md deleteClassroom()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteClassroom/README.md A]]
EditAula -[#darkgoldenrod,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editClassroom/README.md editClassroom()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editClassroom/README.md A]]
EditAula -[#darkgoldenrod,bold]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteClassroom/README.md deleteClassroom()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteClassroom/README.md A]]
EditAula -[#darkgoldenrod]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openClassrooms/README.md openClassrooms()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openClassrooms/README.md A]]
ListRecursos -[#darkgoldenrod,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/createResource/README.md createResource()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/createResource/README.md A]]
ListRecursos -[#darkgoldenrod,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editResource/README.md editResource()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editResource/README.md A]]
ListRecursos -[#darkgoldenrod,bold]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteResource/README.md deleteResource()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteResource/README.md A]]
EditRecurso -[#darkgoldenrod,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editResource/README.md editResource()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editResource/README.md A]]
EditRecurso -[#darkgoldenrod,bold]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/deleteResource/README.md deleteResource()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/deleteResource/README.md A]]
EditRecurso -[#darkgoldenrod]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/openResources/README.md openResources()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/openResources/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
ListCursos -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
ListProfesores -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
ListEdificios -[#darkgoldenrod]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
ListAulas -[#darkgoldenrod]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
ListRecursos -[#darkgoldenrod,bold]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
Generacion -[#darkgoldenrod,bold]-> Consulta: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/viewSchedule/README.md viewSchedule()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/viewSchedule/README.md A]]
Consulta -[#darkgoldenrod,bold]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completeManagement/README.md completeManagement()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completeManagement/README.md A]]
@enduml