@startuml diagrama-contexto-administrador

left to right direction
skinparam linetype polyline

<style>
legend {
  BackGroundColor #f0f0f0;
  'Margin 30
  Padding 10
}
footer {
  HorizontalAlignment left
}

</style>

legend top
    **DASHBOARD DE CONTEXTO** - <i>Casos de uso</i>
    '====
    |<#gray>     | Identificado |<#red>     | Requisitado |<#darkgoldenrod>     | Analizado |<#green>     | Diseñado |<#lightblue>     | Desarrollado |<#blue>     | Probado |<#black>     | Completado |
    | | | | | | | |  | | - FastAPI/React  ||
    | | | | | | | | [[https://raw.githubusercontent.com/mmasias/pySigHor/diseño-spring-angular/images/RUP/99-seguimiento/diagrama-contexto-administrador.svg - Spring/Angular]]  |
    | | | | | | | | [[https://raw.githubusercontent.com/mmasias/pySigHor/diseño-cli-python-http/images/RUP/99-seguimiento/diagrama-contexto-administrador.svg - CLI HTTP]]  |
    | | | | | | | | [[https://raw.githubusercontent.com/mmasias/pySigHor/diseño-cli-python-standalone/images/RUP/99-seguimiento/diagrama-contexto-administrador.svg - CLI Standalone]]  |
    '====
    '[**nombreCasoUso()**] -> Especificación detallada / [**A**] -> Análisis MVC / [**D**] -> Diseño (disponible en ramas específicas) / [**dev**] -> Desarrollo (implementación)
    '====
end legend

footer
**<i>[[https://github.com/mmasias/pySigHor << Volver al repo]]</i>**
end footer

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "PROGRAMAS_ABIERTO" as ListProgramas
state "PROGRAMA_ABIERTO" as EditPrograma
state "CURSOS_ABIERTO" as ListCursos
state "CURSO_ABIERTO" as EditCurso
state "PROFESORES_ABIERTO" as ListProfesores
state "PROFESOR_ABIERTO" as EditProfesor
state "PROFESOR_PREFERENCIAS_ABIERTO" as EditProfesorPreferencias
state "EDIFICIOS_ABIERTO" as ListEdificios
state "EDIFICIO_ABIERTO" as EditEdificio
state "AULAS_ABIERTO" as ListAulas
state "AULA_ABIERTA" as EditAula
state "RECURSOS_ABIERTO" as ListRecursos
state "RECURSO_ABIERTO" as EditRecurso

state "PROFESOR_ASIGNATURAS_ABIERTO" as Asignaciones
state "HORARIO_GENERADO" as Generacion
state "HORARIO_ABIERTO" as Consulta

NoAuth -[#lightblue,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/iniciarSesion/README.md iniciarSesion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/iniciarSesion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/iniciarSesion/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/iniciarSesion/README.md dev]]

Menu -[#green,thickness=2]-> NoAuth: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/cerrarSesion/README.md cerrarSesion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/cerrarSesion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/cerrarSesion/README.md D]]
Menu -[#lightblue,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProgramas/README.md abrirProgramas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProgramas/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirProgramas/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirProgramas/README.md dev]]
Menu -[#lightblue,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirCursos/README.md abrirCursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirCursos/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirCursos/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirCursos/README.md dev]]
Menu -[#lightblue,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProfesores/README.md abrirProfesores()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProfesores/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirProfesores/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirProfesores/README.md dev]]
Menu -[#lightblue]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirEdificios/README.md abrirEdificios()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirEdificios/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirEdificios/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirEdificios/README.md dev]]
Menu -[#lightblue]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirAulas/README.md abrirAulas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirAulas/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirAulas/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirAulas/README.md dev]]
Menu -[#lightblue]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirRecursos/README.md abrirRecursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirRecursos/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirRecursos/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirRecursos/README.md dev]]
Menu -[#green,bold]-> Generacion: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/generarHorario/README.md generarHorario()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/generarHorario/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/generarHorario/README.md D]]
Menu -[#green,bold]-> Consulta: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/consultarHorario/README.md consultarHorario()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/consultarHorario/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/consultarHorario/README.md D]]

EditProfesor -[#lightblue,thickness=2]-> Asignaciones: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/asignarProfesorACurso/README.md asignarProfesorACurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/asignarProfesorACurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/asignarProfesorACurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/asignarProfesorACurso/README.md dev]]

Asignaciones -[#lightblue,thickness=2]-> Asignaciones: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/asignarProfesorACurso/README.md asignarProfesorACurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/asignarProfesorACurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/asignarProfesorACurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/asignarProfesorACurso/README.md dev]]
Asignaciones -[#lightblue,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarProfesor/README.md editarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarProfesor/README.md dev]]
ListProgramas -[#lightblue,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearPrograma/README.md crearPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearPrograma/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearPrograma/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearPrograma/README.md dev]]
ListProgramas -[#lightblue,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarPrograma/README.md editarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarPrograma/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarPrograma/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarPrograma/README.md dev]]
ListProgramas -[#lightblue,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarPrograma/README.md eliminarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarPrograma/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarPrograma/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarPrograma/README.md dev]]
EditPrograma -[#lightblue,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarPrograma/README.md editarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarPrograma/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarPrograma/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarPrograma/README.md dev]]
EditPrograma -[#lightblue,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarPrograma/README.md eliminarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarPrograma/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarPrograma/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarPrograma/README.md dev]]
EditPrograma -[#lightblue,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProgramas/README.md abrirProgramas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProgramas/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirProgramas/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirProgramas/README.md dev]]
ListCursos -[#lightblue,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearCurso/README.md crearCurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearCurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearCurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearCurso/README.md dev]]
ListCursos -[#lightblue,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarCurso/README.md editarCurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarCurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarCurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarCurso/README.md dev]]
ListCursos -[#lightblue,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarCurso/README.md eliminarCurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarCurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarCurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarCurso/README.md dev]]
EditCurso -[#lightblue,thickness=2]-> EditCurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarCurso/README.md editarCurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarCurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarCurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarCurso/README.md dev]]
EditCurso -[#lightblue,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarCurso/README.md eliminarCurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarCurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarCurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarCurso/README.md dev]]
EditCurso -[#lightblue,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirCursos/README.md abrirCursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirCursos/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirCursos/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirCursos/README.md dev]]
ListProfesores -[#lightblue,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearProfesor/README.md crearProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearProfesor/README.md dev]]
ListProfesores -[#lightblue,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarProfesor/README.md editarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarProfesor/README.md dev]]
ListProfesores -[#lightblue,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarProfesor/README.md eliminarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarProfesor/README.md dev]]
EditProfesor -[#lightblue,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarProfesor/README.md editarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarProfesor/README.md dev]]
EditProfesor -[#lightblue,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarProfesor/README.md eliminarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarProfesor/README.md dev]]
EditProfesor -[#lightblue,thickness=2]-> EditProfesorPreferencias: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/configurarPreferenciasProfesor/README.md configurarPreferenciasProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/configurarPreferenciasProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/configurarPreferenciasProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/configurarPreferenciasProfesor/README.md dev]]
EditProfesor -[#lightblue,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProfesores/README.md abrirProfesores()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProfesores/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirProfesores/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirProfesores/README.md dev]]
EditProfesorPreferencias -[#lightblue,thickness=2]-> EditProfesorPreferencias: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/configurarPreferenciasProfesor/README.md configurarPreferenciasProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/configurarPreferenciasProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/configurarPreferenciasProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/configurarPreferenciasProfesor/README.md dev]]
EditProfesorPreferencias -[#lightblue,thickness=2]-> EditProfesor: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarProfesor/README.md editarProfesor()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarProfesor/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarProfesor/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarProfesor/README.md dev]]
ListEdificios -[#lightblue,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearEdificio/README.md crearEdificio()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearEdificio/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearEdificio/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearEdificio/README.md dev]]
ListEdificios -[#lightblue,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarEdificio/README.md editarEdificio()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarEdificio/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarEdificio/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarEdificio/README.md dev]]
ListEdificios -[#lightblue,bold]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarEdificio/README.md eliminarEdificio()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarEdificio/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarEdificio/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarEdificio/README.md dev]]
EditEdificio -[#lightblue,bold]-> EditEdificio: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarEdificio/README.md editarEdificio()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarEdificio/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarEdificio/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarEdificio/README.md dev]]
EditEdificio -[#lightblue,bold]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarEdificio/README.md eliminarEdificio()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarEdificio/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarEdificio/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarEdificio/README.md dev]]
EditEdificio -[#lightblue]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirEdificios/README.md abrirEdificios()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirEdificios/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirEdificios/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirEdificios/README.md dev]]
ListAulas -[#lightblue,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearAula/README.md crearAula()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearAula/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearAula/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearAula/README.md dev]]
ListAulas -[#lightblue,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarAula/README.md editarAula()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarAula/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarAula/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarAula/README.md dev]]
ListAulas -[#lightblue,bold]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarAula/README.md eliminarAula()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarAula/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarAula/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarAula/README.md dev]]
EditAula -[#lightblue,bold]-> EditAula: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarAula/README.md editarAula()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarAula/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarAula/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarAula/README.md dev]]
EditAula -[#lightblue,bold]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarAula/README.md eliminarAula()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarAula/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarAula/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarAula/README.md dev]]
EditAula -[#lightblue]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirAulas/README.md abrirAulas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirAulas/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirAulas/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirAulas/README.md dev]]
ListRecursos -[#lightblue,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearRecurso/README.md crearRecurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearRecurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/crearRecurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/crearRecurso/README.md dev]]
ListRecursos -[#lightblue,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarRecurso/README.md editarRecurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarRecurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarRecurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarRecurso/README.md dev]]
ListRecursos -[#lightblue,bold]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarRecurso/README.md eliminarRecurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarRecurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarRecurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarRecurso/README.md dev]]
EditRecurso -[#lightblue,bold]-> EditRecurso: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarRecurso/README.md editarRecurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarRecurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/editarRecurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/editarRecurso/README.md dev]]
EditRecurso -[#lightblue,bold]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarRecurso/README.md eliminarRecurso()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarRecurso/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/eliminarRecurso/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/eliminarRecurso/README.md dev]]
EditRecurso -[#lightblue]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirRecursos/README.md abrirRecursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirRecursos/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/abrirRecursos/README.md D]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/03-desarrollo/casos-uso/abrirRecursos/README.md dev]]
ListProgramas -[#green,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
ListCursos -[#green,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
ListProfesores -[#green,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
ListEdificios -[#green]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
ListAulas -[#green]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
ListRecursos -[#green,bold]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
Generacion -[#green,bold]-> Consulta: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/consultarHorario/README.md consultarHorario()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/consultarHorario/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/consultarHorario/README.md D]]
Consulta -[#green,bold]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]] [[https://github.com/mmasias/pySigHor/blob/diseño-fastapi-react/RUP/02-diseño/casos-uso/completarGestion/README.md D]]
@enduml
