@startuml createResource-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Recursos Abierto" as RecursosAbierto
rectangle #CDEBA5 ":Collaboration EditResource" as EditResource

package createResource as "createResource()" {
    rectangle #629EF9 CreateResourceView
    rectangle #b5bd68 RecursoController
    rectangle #F2AC4E ResourceRepository
    rectangle #F2AC4E Resource
}

RecursosAbierto -r-> CreateResourceView: createResource()

CreateResourceView -d-> RecursoController: validateMinimalData(codigo, nombre) : boolean

RecursoController --> ResourceRepository: checkUniqueness(codigo) : boolean

CreateResourceView --> RecursoController: crearRecurso(codigo, nombre) : Recurso

RecursoController --> ResourceRepository: create(codigo, nombre) : Recurso

ResourceRepository -- Recurso

CreateResourceView ..> EditResource: <<include>> editarRecurso(recursoNuevo)

@enduml