@startuml deleteProgram-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Programas Abierto" as ProgramasAbierto
rectangle #CDEBA5 ":Programa Abierto" as ProgramaAbierto
rectangle #CDEBA5 ":Collaboration AbrirProgramas" as AbrirProgramas

package deleteProgram as "deleteProgram()" {
    rectangle #629EF9 DeleteProgramView
    rectangle #b5bd68 ProgramaController
    rectangle #F2AC4E ProgramRepository
    rectangle #F2AC4E Program
}

ProgramasAbierto --> DeleteProgramView: eliminarPrograma(programaId)
ProgramaAbierto --> DeleteProgramView: eliminarPrograma(programaId)

DeleteProgramView -d-> ProgramaController: cargarProgramaParaEliminacion(programaId) : Programa

ProgramaController --> ProgramRepository: getById(programaId) : Programa

ProgramRepository -- Programa

DeleteProgramView --> ProgramaController: eliminarPrograma(programaId) : void

ProgramaController --> ProgramRepository: delete(programaId) : void

DeleteProgramView ..> AbrirProgramas: <<include>> openPrograms()

@enduml