@startsalt editCourse-wireframe
{
    <b>EDIT ACADEMIC COURSE</b>
    ===
    {
        <b>Course data:</b>
        --
        {
            {
            {<b>Code:</b> | "CUR-001                     "
            <b>Name:</b> | "Differential Calculus       "}
            {<b>Description:</b> |
                {"Fundamental mathematics course that introduces
                concepts of limits, derivatives and applications
                of differential calculus                      "}}
            --
            {<b>Academic data:</b>
            <b>Credits:</b> | "4  "
            <b>Theoretical hours/week:</b> | "3  "
            <b>Practical hours/week:</b> | "2  "}
            --
            {<b>Academic program:</b> | ^Industrial and Systems Engineering^}
            }
        }

        ~~

        {[Save changes] | [Continue editing] | [Cancel]}
    }
}
@endsalt