@startuml deleteTeacher-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Teachers Open" as TeachersOpen
rectangle #CDEBA5 ":Profesor Abierto" as ProfesorAbierto
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores

package deleteTeacher as "deleteTeacher()" {
    rectangle #629EF9 DeleteTeacherView
    rectangle #b5bd68 TeacherController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E Teacher
}

TeachersOpen --> DeleteTeacherView: eliminarProfesor(profesorId)
ProfesorAbierto --> DeleteTeacherView: eliminarProfesor(profesorId)

DeleteTeacherView -d-> TeacherController: cargarProfesorParaEliminacion(profesorId) : Teacher

TeacherController --> TeacherRepository: getById(profesorId) : Teacher

TeacherRepository -- Profesor

DeleteTeacherView --> TeacherController: eliminarProfesor(profesorId) : void

TeacherController --> TeacherRepository: delete(profesorId) : void

DeleteTeacherView ..> AbrirProfesores: <<include>> openTeachers()

@enduml