@startuml deleteTeacher-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto
rectangle #CDEBA5 ":Profesor Abierto" as ProfesorAbierto
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores

package deleteTeacher as "deleteTeacher()" {
    rectangle #629EF9 DeleteTeacherView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E Teacher
}

ProfesoresAbierto --> DeleteTeacherView: eliminarProfesor(profesorId)
ProfesorAbierto --> DeleteTeacherView: eliminarProfesor(profesorId)

DeleteTeacherView -d-> ProfesorController: cargarProfesorParaEliminacion(profesorId) : Profesor

ProfesorController --> TeacherRepository: getById(profesorId) : Profesor

TeacherRepository -- Profesor

DeleteTeacherView --> ProfesorController: eliminarProfesor(profesorId) : void

ProfesorController --> TeacherRepository: delete(profesorId) : void

DeleteTeacherView ..> AbrirProfesores: <<include>> openTeachers()

@enduml