@startsalt createResource-wireframe
{
    <b>CREATE RESOURCE</b>
    ====
    <b>Resource code (*):</b>
    "                                    "
    ====
    <b>Resource name (*):</b>
    "                                    "
    ====
    [ <b>Create Resource</b> ] | [ Cancel ]
    ====
    <size:9><i>(*) Required fields</i></size>
    <size:9><i>After creation, the complete resource</i></size>
    <size:9><i>editing will open automatically.</i></size>
}
@endsalt