@startuml configureTeacherPreferences-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Teacher Open" as TeacherOpen
rectangle #CDEBA5 ":Collaboration EditTeacher" as EditTeacher

package configureTeacherPreferences as "configureTeacherPreferences()" {
    rectangle #629EF9 ConfigurePreferencesTeacherView
    rectangle #b5bd68 PreferencesTeacherController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E ResourceRepository
    rectangle #F2AC4E Teacher
    rectangle #F2AC4E TeacherPreferences
    rectangle #F2AC4E Resource
}

TeacherOpen -r-> ConfigurePreferencesTeacherView: configureTeacherPreferences(teacherId)

ConfigurePreferencesTeacherView -d-> PreferencesTeacherController: loadTeacherPreferences(teacherId)

PreferencesTeacherController --> TeacherRepository: getWithPreferences(teacherId) : Teacher
PreferencesTeacherController --> ResourceRepository: getAvailableResources() : List<Resource>

ConfigurePreferencesTeacherView --> PreferencesTeacherController: modifyPriorityOrder(newOrder) : boolean

PreferencesTeacherController --> TeacherRepository: updatePreferences(teacherId, preferences) : boolean

TeacherRepository -- Teacher
TeacherRepository -- TeacherPreferences
ResourceRepository -- Resource

ConfigurePreferencesTeacherView ..> EditTeacher: <<include>> editTeacher(teacherId)

@enduml