@startsalt createProgram-wireframe
{
    <b>CREATE NEW ACADEMIC PROGRAM</b>
    ===
    {
        <b>Program name:</b> | [                                              ]
        --
        <i>The code will be generated automatically</i>
        <i>The program will be created active by default</i>
    }
    
    ~~
    
    {[Create program] | [Cancel]}
}

@endsalt