@startsalt editBuilding-wireframe
{
    <b>EDIT BUILDING</b>
    ===
    {
        <b>Building data:</b>
        --
        {
            {
            {<b>Code:</b> | "EDIF-001                    "
            <b>Name:</b> | "Central Building             "}
            {<b>Location:</b> | "University Campus            "
            <b>Description:</b> | "Main classroom building      "}
            {<b>Observations:</b> |
                {"Large capacity classroom building
                for lecture courses. Features modern
                audiovisual equipment                "}}
            }
        }

        ~~

        {[Save changes] | [Continue editing] | [Cancel]}
    }
}
@endsalt