@startuml editResource
skinparam linetype polyline

state editResource as "editResource()" {
    state " " as PresentingData
    state " " as ModifyingData
    state c1 <<choice>>
    state c2 <<choice>>
    
    [*] -[#green]-> PresentingData
    note on link
    <b>Administrator</b> requests edit
    end note
    
    PresentingData -[#green]-> ModifyingData
    note on link
    <b>System</b> presents
    • código del recurso
    • nombre del recurso
    • descripción del recurso
    end note
    
    ModifyingData -[#green]-> c1
    note on link
    <b>Administrator</b> introduce
    modificaciones (opcional)
    end note
    
    c1 -[#green]-> c2
    note on link
    <b>Administrator</b> requests guardar
    end note
    
    c2 -[#red]-> PresentingData
    note on link
    código del recurso
    ya existe
    end note
    
    c2 -[#green]-> PresentingData
    note on link
    recurso actualizado
    continuar editando
    end note
    
    c1 -[#green]-> [*]
    note on link
    <b>Administrator</b> requests finalizar
    transferir a openResources()
    end note
}

editResource -[#green]-> RECOURSES_OPEN
note on link
openResources()
end note

@enduml