@startuml editProgram-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Programas Abierto" as ProgramasAbierto
rectangle #CDEBA5 ":Collaboration CreateProgram" as CreateProgram
rectangle #CDEBA5 ":Programas Abierto" as ProgramasAbiertoSalida

package editProgram as "editProgram()" {
    rectangle #629EF9 EditProgramView
    rectangle #b5bd68 ProgramaController
    rectangle #F2AC4E ProgramRepository
    rectangle #F2AC4E Program
}


ProgramasAbierto --> EditProgramView: editarPrograma(programaId)
CreateProgram --> EditProgramView: editarPrograma(programaNuevo)

EditProgramView -d-> ProgramaController: cargarPrograma(programaId) : Programa

ProgramaController --> ProgramRepository: getById(programaId) : Programa

ProgramRepository -- Programa

EditProgramView --> ProgramaController: modificarCampos(programa) : void

EditProgramView --> ProgramaController: guardarPrograma(programa) : void

ProgramaController --> ProgramRepository: update(programa) : void

EditProgramView ..> ProgramasAbiertoSalida: openPrograms()

@enduml