@startsalt openClassrooms-wireframe
{ 
<b>CLASSROOMS MANAGEMENT</b>  
===
{+  ID | NAME | CAPACITY | BUILDING | ACTION
  --|--|--|--|--
  001 | Room 101 | 30 | Main Building | [Edit]
  002 | Room 102 | 25 | Main Building | [Edit]
  003 | Lab 201 | 20 | Laboratories Building | [Edit]
  004 | Main Auditorium | 100 | Main Building | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt