@startuml createClassroom-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Aulas Abierto" as AulasAbierto
rectangle #CDEBA5 ":Collaboration EditClassroom" as EditClassroom

package createClassroom as "createClassroom()" {
    rectangle #629EF9 CreateClassroomView
    rectangle #b5bd68 AulaController
    rectangle #F2AC4E ClassroomRepository
    rectangle #F2AC4E Classroom
}

AulasAbierto -r-> CreateClassroomView: createClassroom()

CreateClassroomView -d-> AulaController: validateMinimalData(codigo, nombre, edificio) : boolean

AulaController --> ClassroomRepository: checkUniqueness(codigo) : boolean

CreateClassroomView --> AulaController: crearAula(codigo, nombre, edificio) : Aula

AulaController --> ClassroomRepository: create(codigo, nombre, edificio) : Aula

ClassroomRepository -- Aula

CreateClassroomView ..> EditClassroom: <<include>> editarAula(aulaNueva)

@enduml