@startsalt editResource-wireframe
{
    <b>EDIT RESOURCE</b>
    ====
    <b>Resource code (*):</b>
    "PROY-001                            "
    ====
    <b>Resource name (*):</b>
    "Multimedia Projector                "
    ====
    <b>Resource description:</b>
    {
        "HD 1080p projector with connections"
        "HDMI, VGA and USB. Includes remote"
        "control and connection cables.    "
        "Ideal for presentations and classes"
    }
    ====
    [ <b>Save and Continue</b> ] | [ <b>Save and Finish</b> ] | [ Cancel ]
    ====
    <size:9><i>(*) Required fields</i></size>
    <size:9><i>Changes are saved automatically</i></size>
    <size:9><i>when pressing "Save and Continue".</i></size>
}
@endsalt