@startsalt openPrograms-wireframe
{ 
<b>ACADEMIC PROGRAMS MANAGEMENT</b>  
===
{+  CODE | NAME | DESCRIPTION | ACTION
  --|--|--|--
  GII | Computer Engineering | Bachelor in Computer Engineering | [Edit]
  GIOI | Industrial Organization Engineering | Bachelor in Industrial Organization Engineering | [Edit]
  GXYZ | Program name | Program description | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt