@startsalt createCourse-wireframe
{
    <b>CREATE ACADEMIC COURSE</b>
    ===
    {
        <b>Course minimum data:</b>
        --
        {
            <b>Course name (*):</b>
            "                                        "
            --
            <i>(*) Required field</i>
            <i>Other data will be completed during editing</i>
        }

        ~~

        {[Create course] | [Cancel]}
    }
}
@endsalt