@startuml createTeacher

skinparam linetype polyline

state createTeacher as "createTeacher()" {

    state " " as RequestingData
    state " " as CreandoProfesor

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests create new
    end note    
    
    RequestingData -[#green]-> CreandoProfesor
    note on link
    <b>System</b> presents solicitud de datos mínimos del profesor
    • Código del profesor (obligatorio)
    • Nombres del profesor (obligatorio)
    • Apellidos del profesor (obligatorio)
    • Permite requestsr crear profesor
    • Permite requestsr cancelar creación
    end note
    
    CreandoProfesor -[#green]-> [*]
    note on link
    <b>Administrator</b> proporciona datos mínimos
    <b>System</b> crea profesor y transfiere a edición
    end note
}

crearProfesor -[#green]-> TEACHER_OPEN
note on link
editarProfesor(profesorNuevo)
end note

crearProfesor -[#blue]-> TEACHERS_OPEN
note on link
cancelar creación
end note

@enduml