@startuml login-analysis
skinparam linetype polyline

actor UsuarioNoRegistrado
package login as "login()" {
    rectangle #629EF9 LoginView
    rectangle #b5bd68 IniciarSessionController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
    rectangle #F2AC4E Sesion
}
rectangle #CDEBA5 ":System Available" as SystemAvailable

UsuarioNoRegistrado -r-> LoginView: iniciarSesion(usuario, contraseña)

LoginView -d-> IniciarSessionController: autenticar(usuario, contraseña) : Sesion

IniciarSessionController --> UsuarioRepository: validarCredenciales(usuario, contraseña) : Usuario

UsuarioRepository -- Usuario

IniciarSessionController --> Sesion: crearSesion(usuario) : Sesion

LoginView -r-> SystemAvailable: sistemaDisponible(administrador)



@enduml