@startuml deleteClassroom

skinparam linetype polyline

state deleteClassroom as "deleteClassroom()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoAula

    [*] -[#green]-> ConfirmandoEliminacion 
    note on link
    <b>Administrator</b> requests delete
    end note    
    
    ConfirmandoEliminacion -[#green]-> EliminandoAula
    note on link
    <b>System</b> presents información del aula a eliminar
    • Código, nombre del aula
    • Edificio asociado, capacidad
    • Tipo, recursos, observaciones
    • Presenta advertencia de eliminación
    • Permite requestsr confirmar eliminación
    • Permite requestsr cancelar eliminación
    end note
    
    EliminandoAula -[#green]-> [*]
    note on link
    <b>Administrator</b> requests confirmación de eliminación
    <b>System</b> permite requestsr confirmar eliminación
    <b>Administrator</b> requests confirmar eliminación
    end note
}

eliminarAula -[#green]-> CLASSROOMS_OPEN
note on link
<<include>> openClassrooms() - lista actualizada
end note

eliminarAula -[#blue]-> CLASSROOMS_OPEN
note on link
<<include>> openClassrooms() - cancelar eliminación
end note

@enduml