@startuml openTeachers

skinparam linetype polyline

state openTeachers as "openTeachers()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests abrir profesores
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents teacher list
    • Código, nombre, apellidos de cada profesor
    • Permite request filter list
    • Permite request create new
    • Permite request delete
    • Permite request edit
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

abrirProfesores -[#green]-> TEACHER_OPEN
note on link
editTeacher()
end note

abrirProfesores -[#green]-> TEACHER_OPEN
note on link
createTeacher()
end note

abrirProfesores -[#green]-> TEACHERS_OPEN
note on link
deleteTeacher()
end note

abrirProfesores -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml