@startuml openResources-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":System Available" as SystemAvailable
package openResources as "openResources()" {
    rectangle #629EF9 ListarRecursosView
    rectangle #b5bd68 ResourcesController
    rectangle #F2AC4E ResourceRepository
    rectangle #F2AC4E Resource
}

rectangle #CDEBA5 ":System Available" as SystemAvailableSalida
rectangle #CDEBA5 ":Collaboration CreateResource" as CreateResource
rectangle #CDEBA5 ":Collaboration EditResource" as EditResource
rectangle #CDEBA5 ":Collaboration DeleteResource" as DeleteResource

SystemAvailable -r-> ListarRecursosView: openResources()

ListarRecursosView -d-> ResourcesController: listResources() : List<Resource>

ResourcesController --> ResourceRepository: getAll() : List<Resource>

ResourceRepository -- Recurso

ListarRecursosView --> ResourcesController: filterResources(criteria) : List<Resource>

ResourcesController --> ResourceRepository: findByCriteria(criteria) : List<Resource>

ListarRecursosView ..> SystemAvailableSalida: completeManagement()
ListarRecursosView ..> CreateResource: createResource()
ListarRecursosView ..> EditResource: editResource()
ListarRecursosView ..> DeleteResource: deleteResource()

@enduml