@startuml deleteProgram

skinparam linetype polyline

state deleteProgram as "deleteProgram()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoPrograma

    [*] -[#green]-> ConfirmandoEliminacion 
    note on link
    <b>Administrator</b> requests delete
    end note    
    
    ConfirmandoEliminacion -[#green]-> EliminandoPrograma
    note on link
    <b>System</b> presents información del programa a eliminar
    • Código, nombre, descripción del programa
    • Presenta advertencia de eliminación
    • Permite request confirmar eliminación
    • Permite request cancelar eliminación
    end note
    
    EliminandoPrograma -[#green]-> [*]
    note on link
    <b>Administrator</b> requests confirmación de eliminación
    <b>System</b> permite request confirmar eliminación
    <b>Administrator</b> requests confirmar eliminación
    end note
}

eliminarPrograma -[#green]-> PROGRAMS_OPEN
note on link
<<include>> openPrograms() - lista actualizada
end note

eliminarPrograma -[#blue]-> PROGRAMS_OPEN
note on link
<<include>> openPrograms() - cancelar eliminación
end note

@enduml