@startuml createClassroom

skinparam linetype polyline

state createClassroom as "createClassroom()" {

    state " " as RequestingData
    state " " as CreatingClassroom

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests crear aula nueva
    end note    
    
    RequestingData -[#green]-> CreatingClassroom
    note on link
    <b>System</b> presents solicitud de datos mínimos del aula
    • Código del aula (obligatorio)
    • Nombre del aula (obligatorio)
    • Edificio asociado (obligatorio)
    • Permite request crear aula
    • Permite request cancel creation
    end note
    
    CreatingClassroom -[#green]-> [*]
    note on link
    <b>Administrator</b> provides minimal data
    <b>System</b> crea aula y transfiere a edición
    end note
}

createClassroom -[#green]-> CLASSROOM_OPEN
note on link
editClassroom(newClassroom)
end note

createClassroom -[#blue]-> CLASSROOMS_OPEN
note on link
cancel creation
end note

@enduml