@startuml createClassroom

skinparam linetype polyline

state createClassroom as "createClassroom()" {

    state " " as RequestingData
    state " " as CreandoAula

    [*] -[#green]-> RequestingData 
    note on link
    <b>Administrator</b> requests crear aula nueva
    end note    
    
    RequestingData -[#green]-> CreandoAula
    note on link
    <b>System</b> presents solicitud de datos mínimos del aula
    • Código del aula (obligatorio)
    • Nombre del aula (obligatorio)
    • Edificio asociado (obligatorio)
    • Permite requestsr crear aula
    • Permite requestsr cancelar creación
    end note
    
    CreandoAula -[#green]-> [*]
    note on link
    <b>Administrator</b> proporciona datos mínimos
    <b>System</b> crea aula y transfiere a edición
    end note
}

crearAula -[#green]-> CLASSROOM_OPEN
note on link
editarAula(aulaNueva)
end note

crearAula -[#blue]-> CLASSROOMS_OPEN
note on link
cancelar creación
end note

@enduml