@startuml

Teacher -d- Course : teaches

Course -r-* Program

package UniversityCampus {
    Building *-u- Classroom
}

Schedule o-- Classroom
Schedule o-d- Course
Schedule o-- Teacher

Teacher ..> Resource : prefers
Classroom ..> Resource : offers

Course .. TimeBlock


@enduml