@startuml deleteTeacher

skinparam linetype polyline

state deleteTeacher as "deleteTeacher()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoProfesor

    [*] -[#green]-> ConfirmandoEliminacion 
    note on link
    <b>Administrator</b> requests delete
    end note    
    
    ConfirmandoEliminacion -[#green]-> EliminandoProfesor
    note on link
    <b>System</b> presents información del profesor a eliminar
    • Código, nombres, apellidos del profesor
    • Correo electrónico, teléfono
    • Observaciones, cursos asignados
    • Presenta advertencia de eliminación
    • Permite request confirmar eliminación
    • Permite request cancelar eliminación
    end note
    
    EliminandoProfesor -[#green]-> [*]
    note on link
    <b>Administrator</b> requests confirmación de eliminación
    <b>System</b> permite request confirmar eliminación
    <b>Administrator</b> requests confirmar eliminación
    end note
}

eliminarProfesor -[#green]-> TEACHERS_OPEN
note on link
<<include>> openTeachers() - lista actualizada
end note

eliminarProfesor -[#blue]-> TEACHERS_OPEN
note on link
<<include>> openTeachers() - cancelar eliminación
end note

@enduml
