@startsalt createTeacher-wireframe
{
    <b>CREATE TEACHER</b>
    ===
    {
        <b>Teacher minimum data:</b>
        --
        {
            <b>Teacher code (*):</b>
            "                                        "
            <b>First names (*):</b>
            "                                        "
            <b>Last names (*):</b>
            "                                        "
            --
            <i>(*) Required fields</i>
            <i>Other data will be completed during editing</i>
        }

        ~~

        {[Create teacher] | [Cancel]}
    }
}
@endsalt