@startsalt deleteCourse-wireframe
{
    <b>DELETE ACADEMIC COURSE</b>
    ===
    {
        <b>Are you sure you want to delete this course?</b>
        --
        {
            {<b>Code:</b> | CUR-001
            <b>Name:</b> | Differential Calculus}
            {<b>Description:</b> |
            {
                Fundamental mathematics course that introduces
                concepts of limits, derivatives and applications
                of differential calculus
            }}
            {<b>Credits:</b> | 4
            <b>Theoretical hours/week:</b> | 3
            <b>Practical hours/week:</b> | 2
            <b>Academic program:</b> | Industrial and Systems Engineering}
            --
            <b>⚠️ WARNING: This action is irreversible</b>
            <i>The course and all associated information will be permanently deleted</i>
        }

        ~~

        {[Confirm deletion] | [Cancel]}
    }
}
@endsalt