@startsalt openResources-wireframe
{ 
<b>RESOURCES MANAGEMENT</b>  
===
{+  ID | NAME | DESCRIPTION | ACTION
  --|--|--|--
  001 | Projector | Standard multimedia projector | [Edit]
  002 | Computer | Desktop PC for classrooms | [Edit]
  003 | Digital Board | Interactive board | [Edit]
  004 | Laboratory | Specialized equipment | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt