@startsalt deleteTeacher-wireframe
{
    <b>DELETE TEACHER</b>
    ===
    {
        <b>Are you sure you want to delete this teacher?</b>
        --
        {
            {<b>Code:</b> | PROF-001
            <b>Name:</b> | Juan Carlos García López}
            {<b>Email:</b> | jgarcia@universidad.edu
            <b>Phone:</b> | +51 999 123 456}
            {<b>Observations:</b> |
            {
                Specialized teacher in algorithms
                and data structures. Experience
                in educational software development.
            }}
            {<b>Assigned courses:</b> | 3 active courses
            <b>Preferences:</b> | Configured (classrooms with projector)}
            --
            <b>⚠️ WARNING: This action is irreversible</b>
            <i>The teacher and all associated information will be permanently deleted</i>
        }

        ~~

        {[Confirm deletion] | [Cancel]}
    }
}
@endsalt
