@startuml editTeacher-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Teachers Open" as TeachersOpen
rectangle #CDEBA5 ":Profesor Abierto" as ProfesorAbierto
rectangle #CDEBA5 ":Collaboration CreateTeacher" as CreateTeacher
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores

package editTeacher as "editTeacher()" {
    rectangle #629EF9 EditTeacherView
    rectangle #b5bd68 TeacherController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E Teacher
}

TeachersOpen --> EditTeacherView: editarProfesor(profesorId)
ProfesorAbierto --> EditTeacherView: editarProfesor(profesorId)
CreateTeacher --> EditTeacherView: editarProfesor(profesorNuevo)

EditTeacherView -d-> TeacherController: cargarProfesorParaEdición(profesorId) : Teacher

TeacherController --> TeacherRepository: getById(profesorId) : Teacher

EditTeacherView --> TeacherController: modificarCampos(profesorId, cambios) : boolean

TeacherController --> TeacherRepository: update(profesor) : boolean

TeacherRepository -- Profesor

EditTeacherView ..> AbrirProfesores: <<include>> openTeachers()

@enduml