@startuml logout

skinparam linetype polyline

state logout as "logout()" {

    state " " as SolicitandoCierre
    state " " as ConfirmandoCierre  
    state c <<choice>>

    [*] -[#green]-> SolicitandoCierre 
    note on link
    <b>Administrator</b> requests cerrar sesión
    end note    
    
    SolicitandoCierre -[#green]-> ConfirmandoCierre
    note on link
    <b>System</b> presents confirmación
    ¿Desea cerrar la sesión activa?
    end note
    
    ConfirmandoCierre -[#green]-> c
    note on link
    <b>System</b> permite confirmar y cancelar
    end note
    

}
    c -[#blue]-> SYSTEM_AVAILABLE
    note on link
    <b>Administrator</b> requests cancelar cierre
    end note
    
    c -[#green]-> SESSION_CLOSED
    note on link
    Administrador → UsuarioNoRegistrado
    login()
    end note


'cerrarSesion -[#green]-> SESSION_CLOSED
'note on link
'Administrador → UsuarioNoRegistrado
'login()
'end note

@enduml