@startuml editClassroom-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Aulas Abierto" as AulasAbierto
rectangle #CDEBA5 ":Aula Abierta" as AulaAbierta
rectangle #CDEBA5 ":Collaboration CreateClassroom" as CreateClassroom
rectangle #CDEBA5 ":Collaboration AbrirAulas" as AbrirAulas

package editClassroom as "editClassroom()" {
    rectangle #629EF9 EditClassroomView
    rectangle #b5bd68 AulaController
    rectangle #F2AC4E ClassroomRepository
    rectangle #F2AC4E Classroom
}

AulasAbierto --> EditClassroomView: editarAula(aulaId)
AulaAbierta --> EditClassroomView: editarAula(aulaId)
CreateClassroom --> EditClassroomView: editarAula(aulaNueva)

EditClassroomView -d-> AulaController: cargarAulaParaEdición(aulaId) : Aula

AulaController --> ClassroomRepository: getById(aulaId) : Aula

EditClassroomView --> AulaController: modificarCampos(aulaId, cambios) : boolean

AulaController --> ClassroomRepository: update(aula) : boolean

ClassroomRepository -- Aula

EditClassroomView ..> AbrirAulas: <<include>> openClassrooms()

@enduml