@startuml deleteCourse-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":Cursos Abierto" as CursosAbierto
rectangle #CDEBA5 ":Curso Abierto" as CursoAbierto
rectangle #CDEBA5 ":Collaboration AbrirCursos" as AbrirCursos

package deleteCourse as "deleteCourse()" {
    rectangle #629EF9 DeleteCourseView
    rectangle #b5bd68 CursoController
    rectangle #F2AC4E CourseRepository
    rectangle #F2AC4E Course
}

CursosAbierto --> DeleteCourseView: eliminarCurso(cursoId)
CursoAbierto --> DeleteCourseView: eliminarCurso(cursoId)

DeleteCourseView -d-> CursoController: cargarCursoParaEliminacion(cursoId) : Curso

CursoController --> CourseRepository: getById(cursoId) : Curso

CourseRepository -- Curso

DeleteCourseView --> CursoController: eliminarCurso(cursoId) : void

CursoController --> CourseRepository: delete(cursoId) : void

DeleteCourseView ..> AbrirCursos: <<include>> openCourses()

@enduml