@startsalt editTeacher-wireframe
{
    <b>EDIT TEACHER</b>
    ===
    {
        <b>Teacher data:</b>
        --
        {
            {
            {<b>Code:</b> | "PROF-001                    "
            <b>First names:</b> | "Juan Carlos                  "}
            {<b>Last names:</b> | "García López                 "
            <b>Email:</b> | "jgarcia@universidad.edu      "}
            {<b>Phone:</b> | "+51 999 123 456              "
            <b>Observations:</b> |
                {"Specialized teacher in algorithms
                and data structures. Experience
                in educational software development  "}}
            }
        }

        ~~

        {[Save changes] | [Continue editing] | [Cancel]}
    }
}
@endsalt