@startuml openCourses

skinparam linetype polyline

state openCourses as "openCourses()" {

    state " " as ShowingList
    state " " as FilteringList

    [*] -[#green]-> ShowingList 
    note on link
    <b>Administrator</b> requests to open courses
    end note    
    
    ShowingList -[#green]-> FilteringList
    note on link
    <b>System</b> presents course list
    • Code, name, description of each course
    <b>System</b> allows
    • request to filter list
    • request to create new course
    • request to delete course
    • request to edit course
    end note
    
    FilteringList -[#green]-> FilteringList
    note on link
    <b>Administrator</b> requests to filter list
    <b>System</b> presents filtered list
    end note
    
    FilteringList -[#green]-> [*]
    note on link
    <b>Administrator</b> requests one of the options
    end note
}

openCourses -[#green]-> COURSE_OPEN
note on link
editCourse()
end note

openCourses -[#green]-> COURSE_OPEN
note on link
createCourse()
end note

openCourses -[#green]-> COURSES_OPEN
note on link
deleteCourse()
end note

openCourses -[#green]-> SYSTEM_AVAILABLE
note on link
completeManagement()
end note

@enduml