@startsalt openCourses-wireframe
{ 
<b>ACADEMIC COURSES MANAGEMENT</b>  
===
{+  CODE | NAME | DESCRIPTION | ACTION
  --|--|--|--
  MAT101 | Mathematics I | Differential and integral calculus | [Edit]
  FIS201 | General Physics | Mechanics and thermodynamics | [Edit]
  CXYZ | Course name | Course description | [Edit]
  }
  ~~
  {<b>SEARCH:</b> [                                       ] | [Filter]}
  ~~
  {[Create new] | [Delete selected] | [Exit]}
}

@endsalt