@startuml openTeachers-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":System Available" as SystemAvailable
package openTeachers as "openTeachers()" {
    rectangle #629EF9 OpenTeachersView
    rectangle #b5bd68 TeachersController
    rectangle #F2AC4E TeacherRepository
    rectangle #F2AC4E Teacher
}

rectangle #CDEBA5 ":System Available" as SystemAvailableSalida
rectangle #CDEBA5 ":Collaboration CreateTeacher" as CreateTeacher
rectangle #CDEBA5 ":Collaboration EditTeacher" as EditTeacher
rectangle #CDEBA5 ":Collaboration DeleteTeacher" as DeleteTeacher

SystemAvailable -r-> OpenTeachersView: openTeachers()

OpenTeachersView -d-> TeachersController: listTeachers() : List<Teacher>

TeachersController --> TeacherRepository: getAll() : List<Teacher>

TeacherRepository -- Teacher

OpenTeachersView --> TeachersController: filterTeachers(criteria) : List<Teacher>

TeachersController --> TeacherRepository: findByCriteria(criteria) : List<Teacher>

OpenTeachersView ..> SystemAvailableSalida: completeManagement()
OpenTeachersView ..> CreateTeacher: createTeacher()
OpenTeachersView ..> EditTeacher: editTeacher()
OpenTeachersView ..> DeleteTeacher: deleteTeacher()

@enduml