@startsalt deleteBuilding-wireframe
{
    <b>DELETE BUILDING</b>
    ===
    {
        <b>Are you sure you want to delete this building?</b>
        --
        {
            {<b>Code:</b> | EDIF-001
            <b>Name:</b> | Central Building}
            {<b>Location:</b> | University Campus
            <b>Description:</b> | Main classroom building}
            {<b>Observations:</b> |
            {
                Building with large capacity classrooms
                for lecture courses. Features modern
                audiovisual equipment.
            }}
            {<b>Associated classrooms:</b> | 15 registered classrooms
            <b>Total capacity:</b> | 850 students}
            --
            <b>⚠️ WARNING: This action is irreversible</b>
            <i>The building and all associated information will be permanently deleted</i>
        }

        ~~

        {[Confirm deletion] | [Cancel]}
    }
}
@endsalt