@startuml deleteResource
skinparam linetype polyline

state deleteResource as "deleteResource()" {
    state " " as PresentingConfirmation
    state " " as AwaitingDecision
    state c <<choice>>
    
    [*] -[#green]-> PresentingConfirmation
    note on link
    <b>Administrator</b> requests delete
    end note
    
    PresentingConfirmation -[#green]-> AwaitingDecision
    note on link
    <b>System</b> presents
    • código del recurso
    • nombre del recurso
    • descripción del recurso
    • profesores que lo prefieren
    • aulas que lo ofrecen
    • advertencia de eliminación
    end note
    
    AwaitingDecision -[#green]-> c
    note on link
    <b>Administrator</b> requests confirmar eliminación
    end note
    
    AwaitingDecision -[#green]-> [*]
    note on link
    <b>Administrator</b> requests cancelar
    transferir a openResources()
    end note
    
    c -[#red]-> [*]
    note on link
    recurso tiene dependencias críticas
    no se puede eliminar
    transferir a openResources()
    end note
    
    c -[#green]-> [*]
    note on link
    recurso eliminado exitosamente
    transferir a openResources()
    end note
}

deleteResource -[#green]-> RECOURSES_OPEN
note on link
openResources()
end note

@enduml