@startuml completeManagement-analysis
skinparam linetype polyline

rectangle #CDEBA5 ":System Available" as SystemAvailable
package completeManagement as "completeManagement()" {
    rectangle #629EF9 GestionView
    rectangle #b5bd68 CompletarGestionController
    rectangle #F2AC4E PermisosRepository
    rectangle #F2AC4E OpcionesMenu
    rectangle #F2AC4E Sesion
}

rectangle #CDEBA5 ":Collaboration AbrirProgramas" as AbrirProgramas
rectangle #CDEBA5 ":Collaboration AbrirCursos" as AbrirCursos
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores
rectangle #CDEBA5 ":Collaboration AbrirEdificios" as AbrirEdificios
rectangle #CDEBA5 ":Collaboration AbrirAulas" as AbrirAulas
rectangle #CDEBA5 ":Collaboration AbrirRecursos" as AbrirRecursos
rectangle #CDEBA5 ":Collaboration AssignTeacher" as AssignTeacher
rectangle #CDEBA5 ":Collaboration GenerateSchedule" as GenerateSchedule
rectangle #CDEBA5 ":Collaboration ViewSchedule" as ViewSchedule
rectangle #CDEBA5 ":Collaboration CerrarSesion" as CerrarSesion

SystemAvailable -r-> GestionView : disponibilizarSistema()

GestionView -d-> CompletarGestionController: habilitarOpciones(administrador)

CompletarGestionController --> Sesion: getUsuario() : Usuario
CompletarGestionController --> PermisosRepository: obtenerOpciones(usuario) : List<Opcion>
CompletarGestionController --> OpcionesMenu: crearOpciones(opciones) : OpcionesMenu

GestionView --> OpcionesMenu: getOpciones() : List<Opcion>
GestionView ..> AbrirProgramas: openPrograms()
GestionView ..> AbrirCursos: openCourses()
GestionView ..> AbrirProfesores: openTeachers()
GestionView ..> AbrirEdificios: openBuildings()
GestionView ..> AbrirAulas: openClassrooms()
GestionView ..> AbrirRecursos: openResources()
GestionView ..> AssignTeacher: assignTeacherToCourse()
GestionView ..> GenerateSchedule: generateSchedule()
GestionView ..> ViewSchedule: viewSchedule()
GestionView ..> CerrarSesion: logout()

@enduml