@startuml assignTeacherToCourse

skinparam linetype polyline

state assignTeacherToCourse as "assignTeacherToCourse()" {

    state " " as GestionandoAsignaciones
    state " " as GuardandoAsignaciones 

    [*] -[#green]-> GestionandoAsignaciones 
    note on link
    <b>Administrator</b> requests asignar cursos al profesor
    end note    
    
    GestionandoAsignaciones -[#green]-> GuardandoAsignaciones
    note on link
    <b>System</b> presents gestión de asignaciones
    • Lista de cursos disponibles
    • Lista de cursos ya asignados al profesor
    
    <b>System</b> permite requestsr:
    • asignar curso disponible
    • desasignar curso asignado
    • guardar asignaciones
    • cancelar gestión
    end note
    
    GuardandoAsignaciones -[#green]-> GestionandoAsignaciones
    note on link
    <b>Administrator</b> requests asignar curso disponible
    end note
    
    GuardandoAsignaciones -[#green]-> [*]
    note on link
    <b>Administrator</b> requests guardar y salir
    end note

    GuardandoAsignaciones -[#red]-> [*]
    note on link
    <b>Administrator</b> requests cancelar gestión
    end note

}

asignarProfesorACurso -[#green]-> TEACHER_OPEN
note on link
editTeacher()
end note

asignarProfesorACurso -[#red]-> TEACHER_OPEN
note on link
cancelar gestión
end note

@enduml