@startsalt createClassroom-wireframe
{
    <b>CREATE CLASSROOM</b>
    ===
    {
        <b>Classroom minimum data:</b>
        --
        {
            <b>Classroom code (*):</b>
            "                                        "
            <b>Classroom name (*):</b>
            "                                        "
            <b>Associated building (*):</b>
            ^"Select building..."^
            --
            <i>(*) Required fields</i>
            <i>Other data will be completed during editing</i>
        }

        ~~

        {[Create classroom] | [Cancel]}
    }
}
@endsalt